CREATE TABLE "idk_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idk_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "idk_product_draft" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idk_product_draft_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"productId" integer,
	"draftData" jsonb NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "idk_order_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idk_order_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"orderId" integer NOT NULL,
	"productVariantId" integer NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"unitPrice" numeric(10, 2) NOT NULL,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "idk_order" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idk_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"status" varchar(32) DEFAULT 'pending' NOT NULL,
	"stripeSessionId" varchar(255),
	"printfulOrderId" integer,
	"printfulExternalOrderId" varchar(128),
	"email" varchar(256),
	"shippingAddress" jsonb,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "idk_printful_file" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idk_printful_file_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"productVariantId" integer NOT NULL,
	"placementType" varchar(64) NOT NULL,
	"fileUrl" text NOT NULL,
	"fileHash" varchar(128),
	"printfulFileId" integer,
	"status" varchar(32) DEFAULT 'pending' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "idk_printful_sync_product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idk_printful_sync_product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"productId" integer NOT NULL,
	"printfulSyncProductId" integer NOT NULL,
	"printfulExternalProductId" varchar(128),
	"status" varchar(32) DEFAULT 'synced' NOT NULL,
	"syncedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "idk_product_image" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idk_product_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"productId" integer NOT NULL,
	"url" text NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "idk_product_variant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idk_product_variant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"productId" integer NOT NULL,
	"size" varchar(32) NOT NULL,
	"color" varchar(64) NOT NULL,
	"sku" varchar(128),
	"retailPrice" numeric(10, 2) NOT NULL,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"availabilityStatus" varchar(32) DEFAULT 'active' NOT NULL,
	"printfulVariantId" integer NOT NULL,
	"printfulSyncVariantId" integer,
	"printfulExternalVariantId" varchar(128),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "idk_product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idk_product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" varchar(256) NOT NULL,
	"title" varchar(256) NOT NULL,
	"description" text,
	"status" varchar(32) DEFAULT 'draft' NOT NULL,
	"thumbnailUrl" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "idk_product_draft" ADD CONSTRAINT "idk_product_draft_productId_idk_product_id_fk" FOREIGN KEY ("productId") REFERENCES "public"."idk_product"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idk_order_item" ADD CONSTRAINT "idk_order_item_orderId_idk_order_id_fk" FOREIGN KEY ("orderId") REFERENCES "public"."idk_order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idk_order_item" ADD CONSTRAINT "idk_order_item_productVariantId_idk_product_variant_id_fk" FOREIGN KEY ("productVariantId") REFERENCES "public"."idk_product_variant"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idk_printful_file" ADD CONSTRAINT "idk_printful_file_productVariantId_idk_product_variant_id_fk" FOREIGN KEY ("productVariantId") REFERENCES "public"."idk_product_variant"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idk_printful_sync_product" ADD CONSTRAINT "idk_printful_sync_product_productId_idk_product_id_fk" FOREIGN KEY ("productId") REFERENCES "public"."idk_product"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idk_product_image" ADD CONSTRAINT "idk_product_image_productId_idk_product_id_fk" FOREIGN KEY ("productId") REFERENCES "public"."idk_product"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idk_product_variant" ADD CONSTRAINT "idk_product_variant_productId_idk_product_id_fk" FOREIGN KEY ("productId") REFERENCES "public"."idk_product"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "idk_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "product_draft_product_idx" ON "idk_product_draft" USING btree ("productId");--> statement-breakpoint
CREATE INDEX "order_item_order_idx" ON "idk_order_item" USING btree ("orderId");--> statement-breakpoint
CREATE INDEX "order_status_idx" ON "idk_order" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "order_stripe_session_unique" ON "idk_order" USING btree ("stripeSessionId");--> statement-breakpoint
CREATE INDEX "printful_file_variant_idx" ON "idk_printful_file" USING btree ("productVariantId");--> statement-breakpoint
CREATE INDEX "printful_file_placement_idx" ON "idk_printful_file" USING btree ("placementType");--> statement-breakpoint
CREATE UNIQUE INDEX "printful_sync_product_unique" ON "idk_printful_sync_product" USING btree ("printfulSyncProductId");--> statement-breakpoint
CREATE INDEX "printful_sync_product_product_idx" ON "idk_printful_sync_product" USING btree ("productId");--> statement-breakpoint
CREATE INDEX "product_image_product_idx" ON "idk_product_image" USING btree ("productId");--> statement-breakpoint
CREATE INDEX "product_variant_product_idx" ON "idk_product_variant" USING btree ("productId");--> statement-breakpoint
CREATE INDEX "product_variant_printful_variant_idx" ON "idk_product_variant" USING btree ("printfulVariantId");--> statement-breakpoint
CREATE INDEX "product_variant_status_idx" ON "idk_product_variant" USING btree ("availabilityStatus");--> statement-breakpoint
CREATE UNIQUE INDEX "product_slug_unique" ON "idk_product" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "product_status_idx" ON "idk_product" USING btree ("status");